apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-front-deployment
  labels:
    app: kube
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube-front-container
        image: kube-front-image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "123Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
